version: "3"

services:
  dev-ledger-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8181:80"
    volumes:
      - ./ledger-bot:/etc/ledger-bot
    restart: always

volumes:
  ledger-bot:
