version: "3"

services:
  ledger-bot:
    image: ghcr.io/dom-tc/ledger-bot:latest
    env_file:
      - env_file
    ports:
      - "8080:80"
    volumes:
      - ./ledger-bot:/etc/ledger-bot
    restart: always

volumes:
  ledger-bot:
