"""Initial events tables.

Revision ID: ada60e3a175e
Revises:
Create Date: 2025-08-24 12:45:41.290554

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ada60e3a175e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "members",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("discord_id", sa.Integer(), nullable=False),
        sa.Column("nickname", sa.String(), nullable=True),
        sa.Column("bot_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_members")),
        sa.UniqueConstraint("discord_id", name=op.f("uq_members_discord_id")),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_name", sa.String(), nullable=False),
        sa.Column("event_description", sa.Text(), nullable=True),
        sa.Column("event_date", sa.DateTime(), nullable=True),
        sa.Column("event_location", sa.String(), nullable=True),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("max_guests", sa.Integer(), nullable=True),
        sa.Column("deposit_value", sa.Integer(), nullable=True),
        sa.Column("creation_date", sa.DateTime(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=True),
        sa.Column("bot_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["host_id"], ["members.id"], name=op.f("fk_events_host_id_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_table(
        "event_members",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("guests", sa.Integer(), nullable=False),
        sa.Column("has_paid", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("HOST", "CONFIRMED", "WAITLIST", "CANCELLED", name="memberstatus"),
            nullable=False,
        ),
        sa.Column("joined_date", sa.DateTime(), nullable=False),
        sa.Column("paid_date", sa.DateTime(), nullable=True),
        sa.Column("bot_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_event_members_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
            name=op.f("fk_event_members_member_id_members"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_members")),
        sa.UniqueConstraint("event_id", "member_id", name="uq_event_member"),
    )
    op.create_table(
        "event_wines",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("wine", sa.String(), nullable=False),
        sa.Column(
            "category",
            sa.Enum("SPARKLING", "WHITE", "RED", "SWEET", "OTHER", name="winecategory"),
            nullable=False,
        ),
        sa.Column("date_added", sa.DateTime(), nullable=False),
        sa.Column("bot_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_event_wines_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_event_wines_member_id_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_wines")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_wines")
    op.drop_table("event_members")
    op.drop_table("events")
    op.drop_table("members")
    # ### end Alembic commands ###
