"""Additional exceptions."""

from .service_errors import (
    BotMessageInvalidEventError,
    BotMessageInvalidTransactionError,
    BotMessageServiceError,
    InvalidRoleError,
    StatsServiceError,
    TransactionApprovedError,
    TransactionCancelledError,
    TransactionInvalidBuyerError,
    TransactionInvalidMemberError,
    TransactionInvalidSellerError,
    TransactionServiceError,
)
from .signal_halt_error import SignalHaltError
from .storage_errors import (
    CurrencyAlreadyExistsError,
    CurrencyCreationError,
    CurrencyQueryError,
    CurrencyStorageError,
    EventAlreadyExistsError,
    EventChannelError,
    EventCreationError,
    EventMemberAlreadyExistsError,
    EventMemberCreationError,
    EventMemberQueryError,
    EventMemberStorageError,
    EventQueryError,
    EventStorageError,
    MemberAlreadyExistsError,
    MemberCreationError,
    MemberQueryError,
    MemberStorageError,
)

__all__ = [
    "BotMessageInvalidEventError",
    "BotMessageInvalidTransactionError",
    "BotMessageServiceError",
    "CurrencyAlreadyExistsError",
    "CurrencyCreationError",
    "CurrencyQueryError",
    "CurrencyStorageError",
    "EventAlreadyExistsError",
    "EventChannelError",
    "EventCreationError",
    "EventMemberAlreadyExistsError",
    "EventMemberCreationError",
    "EventMemberQueryError",
    "EventMemberStorageError",
    "EventQueryError",
    "EventStorageError",
    "InvalidRoleError",
    "MemberAlreadyExistsError",
    "MemberCreationError",
    "MemberQueryError",
    "MemberStorageError",
    "SignalHaltError",
    "StatsServiceError",
    "TransactionApprovedError",
    "TransactionCancelledError",
    "TransactionInvalidBuyerError",
    "TransactionInvalidMemberError",
    "TransactionInvalidSellerError",
    "TransactionServiceError",
]
